# CONFIG FILE SIMPLE-RENAME
Language: en
#METRICS: Enable or Disable Metrics
Metrics: true
#Blacklisted words
BlackList:
  - blaclistedwords
#Blaclisted items / blocks. Use names, NOT IDs 
BlackListID:
  - air
#Max characters
CharacterLimit: 0
Prefix: '[SimpleRename]'
AnvilFeatures: true
# Add &r at the beginning of all the renamed items to avoid Italics
OverrideDefaultFormat: true

